### model
model_name_or_path: meta-llama/Llama-3.1-8B #meta-llama/Llama-3.1-8B
trust_remote_code: true

### method
stage: tc
do_train: true
finetuning_type: lora
lora_target: all
dataset_from_disk: /data/datasets/amazon_wilds_llama_ens
train_mode: weak

### dataset
dataset: amazon_wilds
template: llama3
cutoff_len: 2048
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16
num_labels: 5

### output
ens: true ###################
ens_lr: 0
easy_hard: 0 ##############
output_dir: /data/rw2s_exp/STRONG/llama_naive_ens_1e4_s9
logging_steps: 10
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
seed: 9

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 1000