### model
model_name_or_path: Qwen/Qwen2.5-7B
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: helpful_qwen_logits ###############################
template: qwen
cutoff_len: 2048
max_samples: 103856 #34225  #####################
overwrite_cache: true
preprocessing_num_workers: 16

### output
ens: true ###################
ens_lr: 0
output_dir: /data/DPO/helpful_0.1_5e6_naive_ens_test   ########################
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
