seed: 0
device: 0
track_in_wandb: false
save_path: "/mlbio_scratch/sobotka/w2s"

data:
  path: "/mlbio_scratch/sobotka/data"
  name: "imagenet_c"
  type: "glass_blur/3"
  batch_size: 128 # for training the weak model
  n_threads: 1

ensemble:
  ### ensemble weights optimization
  ensemble_weights_opter_cfg:
    lr: 1e-4  # lr=0 => adaptive weights turned off
  ensemble_weights_init: "uniform" # "uniform", "random", "entropy"
  ensemble_weights_per_sample: false
  reset_ensemble_weights_at_epoch_end_to_uniform: false
  ensemble_weights_freeze_first_frac_of_epochs: 0.5 # easy-sample guided initialization: set to the fraction of epochs where you want to train only on easy samples
  save_ensemble_weights: "all" # "none", "all", "last"

  ### ensemble models
  weak_models:
    - model_name: "alexnet"
      pretrained: false
      load_ckpt: "/mlbio_scratch/sobotka/w2s/imagenet/models/2024-12-05_01-31-57__weak__alexnet__0.pt"
      freeze_backbone: false
      train: false
    - model_name: "alexnet"
      pretrained: false
      load_ckpt: "/mlbio_scratch/sobotka/w2s/imagenet/models/2024-12-05_01-32-40__weak__alexnet__0.pt"
      freeze_backbone: false
      train: false
    - model_name: "alexnet"
      pretrained: false
      load_ckpt: "/mlbio_scratch/sobotka/w2s/imagenet/models/2024-12-05_01-33-14__weak__alexnet__0.pt"
      freeze_backbone: false
      train: false

w2s:
  student_models: # add multiple for bootstrapping
    - model_name: "resnet50_dino"
      pretrained: true
      load_probe_ckpt: null
    # - model_name: "vitb8_dino"
    #   pretrained: true
    #   load_probe_ckpt: null
  add_students_to_ensemble: false

  train_val_test_split: [0.7, 0.1, 0.2] # portion of the test set to train on, eval on the remaining subset of the test set
  teacher_labels_loss_fn_name: "xent" # "xent", "logconf" (Conf method), "adapt_logconf" (V-sup method), "edl" (Bayes)
  teacher_labels_loss_fn_kwargs: null
  gt_labels_loss_fn_name: "xent"
  gt_labels_loss_fn_kwargs: null
  
  n_epochs: 150
  lr: 1e-4
  batch_size: 128

  ### easy-sample guided initialization: set to the number of epochs where you want to train only on easy samples
  ignore_samples_with_disagreement_first_n_epochs: 75

  ### what w2s setups to train/eval
  eval_on_id_val_data: false
  id_val_data_key: null
  eval_on_test_data: true
  test_data_key: "test"

  ### saving/loading
  save_labels: true
  save_embeddings: true
  load_labels: false
  load_embeddings: false
